#!/usr/bin/env bun
// Card tooling. "gen" rewrites src/knowledge/cards.gen.ts from the card files.
// "lint" exits 1 when cards.gen.ts is stale or the card lint reports errors.
import { existsSync } from "node:fs";
import { join } from "node:path";
import { compareText } from "../src/model/index.ts";
import type { Card } from "../src/model/index.ts";
import { lintCards, parseCard, parseCorpus } from "../src/knowledge/index.ts";
import type { CardIssue, CardPack } from "../src/knowledge/index.ts";

const root = join(import.meta.dir, "..");
const GEN_FILE = "src/knowledge/cards.gen.ts";
const SOURCES: { dir: string; pattern: string; pack: CardPack }[] = [
  { dir: "knowledge/cards", pattern: "**/*.md", pack: "core" },
  { dir: "packs/cc-by/cards", pattern: "*.md", pack: "cc-by" },
];
const EXPECTED_COUNTS = { principle: 12, smell: 21, pattern: 15 };

function cardFiles(): { file: string; pack: CardPack }[] {
  const found: { file: string; pack: CardPack }[] = [];
  for (const source of SOURCES) {
    const dir = join(root, source.dir);
    if (!existsSync(dir)) continue;
    for (const rel of new Bun.Glob(source.pattern).scanSync({ cwd: dir })) {
      found.push({ file: `${source.dir}/${rel.replaceAll("\\", "/")}`, pack: source.pack });
    }
  }
  return found.sort((a, b) => compareText(a.file, b.file));
}

function renderGen(files: { file: string; pack: CardPack }[]): string {
  const imports = files.map((f, i) => `import card${i} from "../../${f.file}" with { type: "text" };\n`).join("");
  const entries = files.map((f, i) => `  { file: ${JSON.stringify(f.file)}, pack: ${JSON.stringify(f.pack)}, text: card${i} },\n`).join("");
  const list = files.length === 0 ? "[]" : `[\n${entries}]`;
  return [
    "// Generated by `bun scripts/cards.ts gen`. Do not edit.\n",
    imports,
    "\nexport interface EmbeddedCard {\n  file: string;\n  pack: \"core\" | \"cc-by\";\n  text: string;\n}\n",
    `\nexport const EMBEDDED_CARDS: readonly EmbeddedCard[] = ${list};\n`,
  ].join("");
}

async function readOptional(path: string): Promise<string | null> {
  const file = Bun.file(join(root, path));
  return (await file.exists()) ? await file.text() : null;
}

async function lint(): Promise<number> {
  const files = cardFiles();
  const issues: CardIssue[] = [];
  if ((await readOptional(GEN_FILE)) !== renderGen(files)) {
    issues.push({ level: "error", file: GEN_FILE, message: "stale; run \"bun scripts/cards.ts gen\"" });
  }
  const cards: Card[] = [];
  for (const f of files) {
    try {
      cards.push(parseCard(f.file, await Bun.file(join(root, f.file)).text(), f.pack));
    } catch (error) {
      issues.push({ level: "error", file: f.file, message: (error as Error).message });
    }
  }
  const corpusText = await readOptional("knowledge/corpus.yaml");
  issues.push(
    ...lintCards({
      cards,
      notice: await readOptional("NOTICE"),
      packLicense: await readOptional("packs/cc-by/LICENSE"),
      packNotice: await readOptional("packs/cc-by/NOTICE"),
      corpus: corpusText === null ? [] : parseCorpus(corpusText),
      expectedCounts: EXPECTED_COUNTS,
    }),
  );
  for (const issue of issues) console.log(`${issue.level} ${issue.file}: ${issue.message}`);
  const errors = issues.filter((i) => i.level === "error").length;
  console.error(`${cards.length} cards, ${errors} errors, ${issues.length - errors} warnings`);
  return errors > 0 ? 1 : 0;
}

const command = process.argv[2];
if (command === "gen") {
  const files = cardFiles();
  await Bun.write(join(root, GEN_FILE), renderGen(files));
  console.error(`wrote ${GEN_FILE} with ${files.length} cards`);
} else if (command === "lint") {
  process.exit(await lint());
} else {
  console.error("usage: bun scripts/cards.ts <gen|lint>");
  process.exit(2);
}
