// Generated by `bun scripts/cards.ts gen`. Do not edit.
import card0 from "../../knowledge/cards/patterns/anti-corruption-layer.md" with { type: "text" };
import card1 from "../../knowledge/cards/patterns/backend-for-frontend.md" with { type: "text" };
import card2 from "../../knowledge/cards/patterns/bulkhead.md" with { type: "text" };
import card3 from "../../knowledge/cards/patterns/circuit-breaker.md" with { type: "text" };
import card4 from "../../knowledge/cards/patterns/cqrs.md" with { type: "text" };
import card5 from "../../knowledge/cards/patterns/event-sourcing.md" with { type: "text" };
import card6 from "../../knowledge/cards/patterns/idempotency-key.md" with { type: "text" };
import card7 from "../../knowledge/cards/patterns/modular-monolith.md" with { type: "text" };
import card8 from "../../knowledge/cards/patterns/ports-and-adapters.md" with { type: "text" };
import card9 from "../../knowledge/cards/patterns/queue-based-load-leveling.md" with { type: "text" };
import card10 from "../../knowledge/cards/patterns/retry.md" with { type: "text" };
import card11 from "../../knowledge/cards/patterns/saga.md" with { type: "text" };
import card12 from "../../knowledge/cards/patterns/strangler-fig.md" with { type: "text" };
import card13 from "../../knowledge/cards/patterns/transactional-outbox.md" with { type: "text" };
import card14 from "../../knowledge/cards/principles/assumptions-with-checks.md" with { type: "text" };
import card15 from "../../knowledge/cards/principles/behavior-is-a-promise.md" with { type: "text" };
import card16 from "../../knowledge/cards/principles/coupling-at-short-distance.md" with { type: "text" };
import card17 from "../../knowledge/cards/principles/deep-modules.md" with { type: "text" };
import card18 from "../../knowledge/cards/principles/directed-acyclic-dependencies.md" with { type: "text" };
import card19 from "../../knowledge/cards/principles/hide-volatile-decisions.md" with { type: "text" };
import card20 from "../../knowledge/cards/principles/history-before-restructuring.md" with { type: "text" };
import card21 from "../../knowledge/cards/principles/loosening-needs-a-decision.md" with { type: "text" };
import card22 from "../../knowledge/cards/principles/name-the-quality-scenario.md" with { type: "text" };
import card23 from "../../knowledge/cards/principles/respect-rejected-alternatives.md" with { type: "text" };
import card24 from "../../knowledge/cards/principles/retrieve-decisions-first.md" with { type: "text" };
import card25 from "../../knowledge/cards/principles/single-state-owner.md" with { type: "text" };
import card26 from "../../knowledge/cards/smells/boundary-bypass.md" with { type: "text" };
import card27 from "../../knowledge/cards/smells/cyclic-dependency.md" with { type: "text" };
import card28 from "../../knowledge/cards/smells/god-component.md" with { type: "text" };
import card29 from "../../knowledge/cards/smells/hidden-change-coupling.md" with { type: "text" };
import card30 from "../../knowledge/cards/smells/hotspot.md" with { type: "text" };
import card31 from "../../knowledge/cards/smells/hub-component.md" with { type: "text" };
import card32 from "../../knowledge/cards/smells/layer-violation.md" with { type: "text" };
import card33 from "../../knowledge/cards/smells/modularity-violation.md" with { type: "text" };
import card34 from "../../knowledge/cards/smells/ownership-spread.md" with { type: "text" };
import card35 from "../../knowledge/cards/smells/public-api-break-or-growth.md" with { type: "text" };
import card36 from "../../knowledge/cards/smells/rising-propagation-cost.md" with { type: "text" };
import card37 from "../../knowledge/cards/smells/scattered-functionality.md" with { type: "text" };
import card38 from "../../knowledge/cards/smells/shallow-module.md" with { type: "text" };
import card39 from "../../knowledge/cards/smells/shared-mutable-state.md" with { type: "text" };
import card40 from "../../knowledge/cards/smells/stale-decision.md" with { type: "text" };
import card41 from "../../knowledge/cards/smells/state-ownership-drift.md" with { type: "text" };
import card42 from "../../knowledge/cards/smells/superseded-dependency.md" with { type: "text" };
import card43 from "../../knowledge/cards/smells/unbalanced-coupling.md" with { type: "text" };
import card44 from "../../knowledge/cards/smells/unstable-dependency.md" with { type: "text" };
import card45 from "../../knowledge/cards/smells/unstable-interface.md" with { type: "text" };
import card46 from "../../knowledge/cards/smells/zone-of-pain.md" with { type: "text" };
import card47 from "../../packs/cc-by/cards/cache-aside.md" with { type: "text" };

export interface EmbeddedCard {
  file: string;
  pack: "core" | "cc-by";
  text: string;
}

export const EMBEDDED_CARDS: readonly EmbeddedCard[] = [
  { file: "knowledge/cards/patterns/anti-corruption-layer.md", pack: "core", text: card0 },
  { file: "knowledge/cards/patterns/backend-for-frontend.md", pack: "core", text: card1 },
  { file: "knowledge/cards/patterns/bulkhead.md", pack: "core", text: card2 },
  { file: "knowledge/cards/patterns/circuit-breaker.md", pack: "core", text: card3 },
  { file: "knowledge/cards/patterns/cqrs.md", pack: "core", text: card4 },
  { file: "knowledge/cards/patterns/event-sourcing.md", pack: "core", text: card5 },
  { file: "knowledge/cards/patterns/idempotency-key.md", pack: "core", text: card6 },
  { file: "knowledge/cards/patterns/modular-monolith.md", pack: "core", text: card7 },
  { file: "knowledge/cards/patterns/ports-and-adapters.md", pack: "core", text: card8 },
  { file: "knowledge/cards/patterns/queue-based-load-leveling.md", pack: "core", text: card9 },
  { file: "knowledge/cards/patterns/retry.md", pack: "core", text: card10 },
  { file: "knowledge/cards/patterns/saga.md", pack: "core", text: card11 },
  { file: "knowledge/cards/patterns/strangler-fig.md", pack: "core", text: card12 },
  { file: "knowledge/cards/patterns/transactional-outbox.md", pack: "core", text: card13 },
  { file: "knowledge/cards/principles/assumptions-with-checks.md", pack: "core", text: card14 },
  { file: "knowledge/cards/principles/behavior-is-a-promise.md", pack: "core", text: card15 },
  { file: "knowledge/cards/principles/coupling-at-short-distance.md", pack: "core", text: card16 },
  { file: "knowledge/cards/principles/deep-modules.md", pack: "core", text: card17 },
  { file: "knowledge/cards/principles/directed-acyclic-dependencies.md", pack: "core", text: card18 },
  { file: "knowledge/cards/principles/hide-volatile-decisions.md", pack: "core", text: card19 },
  { file: "knowledge/cards/principles/history-before-restructuring.md", pack: "core", text: card20 },
  { file: "knowledge/cards/principles/loosening-needs-a-decision.md", pack: "core", text: card21 },
  { file: "knowledge/cards/principles/name-the-quality-scenario.md", pack: "core", text: card22 },
  { file: "knowledge/cards/principles/respect-rejected-alternatives.md", pack: "core", text: card23 },
  { file: "knowledge/cards/principles/retrieve-decisions-first.md", pack: "core", text: card24 },
  { file: "knowledge/cards/principles/single-state-owner.md", pack: "core", text: card25 },
  { file: "knowledge/cards/smells/boundary-bypass.md", pack: "core", text: card26 },
  { file: "knowledge/cards/smells/cyclic-dependency.md", pack: "core", text: card27 },
  { file: "knowledge/cards/smells/god-component.md", pack: "core", text: card28 },
  { file: "knowledge/cards/smells/hidden-change-coupling.md", pack: "core", text: card29 },
  { file: "knowledge/cards/smells/hotspot.md", pack: "core", text: card30 },
  { file: "knowledge/cards/smells/hub-component.md", pack: "core", text: card31 },
  { file: "knowledge/cards/smells/layer-violation.md", pack: "core", text: card32 },
  { file: "knowledge/cards/smells/modularity-violation.md", pack: "core", text: card33 },
  { file: "knowledge/cards/smells/ownership-spread.md", pack: "core", text: card34 },
  { file: "knowledge/cards/smells/public-api-break-or-growth.md", pack: "core", text: card35 },
  { file: "knowledge/cards/smells/rising-propagation-cost.md", pack: "core", text: card36 },
  { file: "knowledge/cards/smells/scattered-functionality.md", pack: "core", text: card37 },
  { file: "knowledge/cards/smells/shallow-module.md", pack: "core", text: card38 },
  { file: "knowledge/cards/smells/shared-mutable-state.md", pack: "core", text: card39 },
  { file: "knowledge/cards/smells/stale-decision.md", pack: "core", text: card40 },
  { file: "knowledge/cards/smells/state-ownership-drift.md", pack: "core", text: card41 },
  { file: "knowledge/cards/smells/superseded-dependency.md", pack: "core", text: card42 },
  { file: "knowledge/cards/smells/unbalanced-coupling.md", pack: "core", text: card43 },
  { file: "knowledge/cards/smells/unstable-dependency.md", pack: "core", text: card44 },
  { file: "knowledge/cards/smells/unstable-interface.md", pack: "core", text: card45 },
  { file: "knowledge/cards/smells/zone-of-pain.md", pack: "core", text: card46 },
  { file: "packs/cc-by/cards/cache-aside.md", pack: "cc-by", text: card47 },
];
