// Generated by `bun scripts/cards.ts gen`. Do not edit.

export interface EmbeddedCard {
  file: string;
  pack: "core" | "cc-by";
  text: string;
}

export const EMBEDDED_CARDS: readonly EmbeddedCard[] = [];
